# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Phillips' Blog
email: chris.phillips@uk.ibm.com
description: >-
  Technical blog covering API Connect, IBM DataPower, API Management, Integration,
  Kubernetes, OpenShift, and Cloud Native technologies. Expert insights on API governance,
  microservices architecture, and enterprise integration patterns.
tagline: API, Integration and Governance SME and Enthusiast
baseurl: ""
url: "https://chrisphillips-cminion.github.io"

# SEO Settings
lang: en_US
locale: en_US

# Social Media & SEO
twitter:
  username: cminion
  card: summary_large_image

social:
  name: Chris Phillips
  links:
    - https://twitter.com/cminion
    - https://github.com/ChrisPhillips-cminion
    - https://www.linkedin.com/in/chrisjphillips

# Default SEO image for social sharing
logo: /images/logo.png
social_image: /images/logo.png

# Author defaults
author:
  name: Chris Phillips
  twitter: cminion
  picture: /images/logo.png

highlighter: rouge
excerpt_separator: <!--more-->


twitter_username: cminion
github_username:  ChrisPhillips-cminion

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
# markdown: CommonMark
# commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-commonmark
  - jekyll-include-cache
paginate: 10
paginate_path: "/page:num/"

future: false
site:
  disqus:
    shortname: chrisphillips-blog
disqus:
  shortname: chrisphillips-blog

minima:
  social_links:
    twitter: cminion
    github: ChrisPhillips-cminion
    linkedin: chrisjphillips

exclude:
  - .jekyll-cache


author: ChrisPhillips

